### ISSUE TITLE
光影精灵4装机BigSur在装机二阶段无限重启，无法进行二阶段安装。

### ISSUE THREAD

**Issue by Zhushixuan** [mechtifs/hackintosh-hp-15-cx0#3]
您好，我想问问，是装的bigsur版本太高的原因嘛

**Comment by mechtifs** [comment]
换了一台电脑，这台已经出手了。
有可能是kext版本的问题，最好手动更新一下。
另外确保cfg锁已经关闭，链接po在readme的最底下。
